Fix broken link in README file for some images
datapartnership/syria-economic-monitor pull request #56
Opened 2023-12-13 04:07 UTC by bennyistanto

This PR will fixed broken link in README file for some images, in the annual and monthly crop anomaly section.

2023-12-13 04:10 UTC, bennyistanto commented
Hi @g4brielvs I noticed in my previous PR, there was some broken link on the image. I submitted a new PR for your review.

2023-12-13 21:23 UTC, g4brielvs approved these changes
@bennyistanto Thanks!

2023-12-13 21:25 UTC, g4brielvs requested changes
@bennyistanto Thanks! Could you please resolve the conflict?

2024-01-10 17:39 UTC, g4brielvs approved these changes

2024-01-10 17:39 UTC, merged